name: Build

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
      uses: actions/checkout@v3
      with:
        path: main
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3
  
    - name: cache compiler
      id: cache-compiler
      uses: actions/cache@v3
      env:
        cache-name: cache-gcc-arm
      with:
        path: ${{ github.workspace }}/gcc-arm-none-eabi-9-2019-q4-major
        key: gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux
    - name: download compiler
      if: steps.cache-compiler.outputs.cache-hit != 'true'
      run: |
        wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/RC2.1/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
        tar xjf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
    - name: enable compiler
      run: |
        echo "${{ github.workspace }}/gcc-arm-none-eabi-9-2019-q4-major/bin" >> $GITHUB_PATH
    - name: run cmake
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: ${{github.workspace}}/main/CMakeLists.txt
        configurePreset: default
        configurePresetAdditionalArgs: "['-DCMAKE_C_COMPILER_LAUNCHER=ccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache']"
        buildPreset: default
    - name: Upload App
      uses: actions/upload-artifact@v3
      with:
        name: App
        path: |
          main/build/default/pico_wifi_manager_app*
    - name: Upload libs
      uses: actions/upload-artifact@v3
      with:
        name: Libs
        path: |
          main/build/**/*.a
          main/include/*.h
          main/include/**/*.h
          main/include/**/*.hpp
          main/include/*.hpp
          !**/_deps/
        
